OPENID_SERVER_URL=https://login.microsoftonline.com/8561e204-d946-4a1f-9b5c-59975d5951b4
OPENID_PROVIDER=azure_ad
OPENID_AUTHORIZATION_URL=https://login.microsoftonline.com/8561e204-d946-4a1f-9b5c-59975d5951b4/oauth2/v2.0/authorize
OPENID_TOKEN_URL=https://login.microsoftonline.com/8561e204-d946-4a1f-9b5c-59975d5951b4/oauth2/v2.0/token
OPENID_CLIENT_ID=d9ddb0a0-e94a-40d8-9090-1f4c2464cf0e
OPENID_CLIENT_SECRET=Cr58Q~a.H43BH3CStjwJuV1ANye~EVVhkWpfXbd.
OPENID_LOGOUT_URL=https://login.microsoftonline.com/8561e204-d946-4a1f-9b5c-59975d5951b4/oauth2/v2.0/logout
OPENID_ALLOWED_DOMAINS=login.microsoftonline.com
