customization:
  annotations: {}
  authSecretRef: web-auth-secret
  baiEmitterSecretRef: null
  cloudpakID: null
  cloudpakName: IBM Cloud Pak for Business Automation
  cloudpakVersion: null
  cp4baLicense: false
  customScriptsRef: null
  dedicatedNodeLabel: null
  deployForProduction: true
  disableWSJavaAgent: false
  downloadUrl: []
  enableAuditLog: false
  enableFips: false
  enableMutualTLS: false
  enablePodMonitor: true
  enabledCiphers: null
  ephemeralStorage:
    capacity: 10Gi
    className: null
    definition: null
  isMultipleAz: false
  kubeVersion: ODM on K8s
  labels: {}
  libertyHookRef: null
  logstashCollectorRef: null
  meteringSendPeriod: null
  meteringServerUrl: null
  monitorRef: null
  nodeAffinity: null
  privateCertificateList: null
  productID: null
  productName: null
  productSemVer: null
  productVersion: null
  readOnlyRootFilesystem: true
  runAsUser: ''
  seccompProfile:
    localhostProfile: null
    type: null
  securitySecretRef: null
  sidecar:
    confSecretRef: null
    enabled: false
    image: null
    probes: null
    resources: null
  tolerations: null
  trustedCertificateList: [ digicert-secret,ms-secret ]
  usageMeteringSecretRef: null
  vault: ''
  watcher:
    debug: false
    enabled: false
    schedule: null
dba:
  istio:
    enabled: false
  keytoolInitContainer:
    image: null
    imagePullPolicy: null
    imagePullSecret: null
  ldapSslSecretRef: null
  passwordSecretRef: null
  rootCaSecretRef: null
decisionCenter:
  annotations: {}
  autoscaling:
    behavior: null
    enabled: false
    maxReplicas: 3
    minReplicas: 2
    targetAverageCpuUtilization: 300
    targetAverageMemoryUtilization: 200
    targetAverageUtilization: null
  contextRoot: null
  customPodAntiAffinity: null
  customScriptsRef: null
  customlibPvc: null
  disableAllAuthenticatedUser: false
  disableDbDump: null
  downloadUrl: []
  enableAuditLog: false
  enableMutualTLS: false
  enabled: true
  extendRoleMapping: false
  initContainer:
    command: null
    configOidcRef: null
    configRef: null
    env: null
    existingClaimName: null
    image: null
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 100Mi
  jvmOptionsRef: null
  labels: {}
  libertyHookRef: null
  lifecycleHooksSecretRef: null
  loggingRef: null
  logstashCollectorRef: null
  monitorRef: null
  networkPolicy:
    egress: null
    ingress: null
  nodeAffinity: null
  persistenceLocale: en_US
  podDisruptionBudget: null
  refererList: null
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      ephemeral-storage: 2G
      memory: 4096Mi
    requests:
      cpu: 500m
      ephemeral-storage: 1G
      memory: 1500Mi
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  routeName: null
  sidecar:
    confSecretRef: null
    enabled: false
    image: null
    probes: null
    resources: null
  tagOrDigest: null
  tolerations: null
  topologySpreadConstraints: []
  webConfigRef: null
decisionRunner:
  annotations: {}
  autoscaling:
    behavior: null
    enabled: false
    maxReplicas: 3
    minReplicas: 2
    targetAverageCpuUtilization: 300
    targetAverageMemoryUtilization: 600
    targetAverageUtilization: null
  contextRoot: null
  customPodAntiAffinity: null
  customScriptsRef: null
  downloadUrl: []
  enableAuditLog: false
  enableMutualTLS: false
  enabled: true
  extendRoleMapping: false
  initContainer:
    command: null
    configOidcRef: null
    configRef: null
    env: null
    existingClaimName: null
    image: null
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 100Mi
  jvmOptionsRef: null
  labels: {}
  libertyHookRef: null
  lifecycleHooksSecretRef: null
  loggingRef: null
  logstashCollectorRef: null
  monitorRef: null
  networkPolicy:
    egress: null
    ingress: null
  nodeAffinity: null
  podDisruptionBudget: null
  replicaCount: 1
  resURL: null
  resources:
    limits:
      cpu: 2
      ephemeral-storage: 1G
      memory: 4096Mi
    requests:
      cpu: 500m
      ephemeral-storage: 200Mi
      memory: 512Mi
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  routeName: null
  sidecar:
    confSecretRef: null
    enabled: false
    image: null
    probes: null
    resources: null
  tagOrDigest: null
  tolerations: null
  topologySpreadConstraints: []
decisionServerConsole:
  annotations: {}
  contextRoot: null
  customPodAntiAffinity: null
  customScriptsRef: null
  description: null
  downloadUrl: []
  enableAuditLog: false
  enableMutualTLS: false
  extendRoleMapping: false
  initContainer:
    command: null
    configOidcRef: null
    configRef: null
    env: null
    existingClaimName: null
    image: null
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 100Mi
  jvmOptionsRef: dsc-jvm-options-configmap
  labels: {}
  libertyHookRef: null
  lifecycleHooksSecretRef: null
  loggingRef: null
  logstashCollectorRef: null
  monitorRef: null
  networkPolicy:
    egress: null
    ingress: null
  nodeAffinity: null
  podDisruptionBudget: null
  resources:
    limits:
      cpu: 2
      ephemeral-storage: 1G
      memory: 1024Mi
    requests:
      cpu: 500m
      ephemeral-storage: 200Mi
      memory: 512Mi
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  routeName: null
  runtime:
    webConfigRef: null
  sidecar:
    confSecretRef: null
    enabled: false
    image: null
    probes: null
    resources: null
  tagOrDigest: null
  title: null
  tolerations: null
  topologySpreadConstraints: []
  webConfigRef: null
decisionServerRuntime:
  annotations: {}
  autoscaling:
    behavior: null
    enabled: false
    maxReplicas: 3
    minReplicas: 2
    targetAverageCpuUtilization: 300
    targetAverageMemoryUtilization: 600
    targetAverageUtilization: null
  contextRoot: null
  customPodAntiAffinity: null
  customScriptsRef: null
  dedicated: []
  downloadUrl: []
  enableAuditLog: false
  enableMutualTLS: false
  enableTLSAuth: null
  enabled: true
  extendRoleMapping: false
  initContainer:
    command: null
    configOidcRef: null
    configRef: null
    env: null
    existingClaimName: null
    image: null
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 100Mi
  jvmOptionsRef: dsr-jvm-options-configmap
  labels: {}
  libertyHookRef: null
  lifecycleHooksSecretRef: null
  loggingRef: null
  logstashCollectorRef: null
  monitorRef: null
  networkPolicy:
    egress: null
    ingress: null
  nodeAffinity: null
  podDisruptionBudget: null
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      ephemeral-storage: 1G
      memory: 4096Mi
    requests:
      cpu: 500m
      ephemeral-storage: 200Mi
      memory: 512Mi
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  routeName: null
  sidecar:
    confSecretRef: null
    enabled: false
    image: null
    probes: null
    resources: null
  tagOrDigest: null
  tolerations: null
  topologySpreadConstraints: []
  webConfigRef: null
  xuConfigRef: ds-runtime-xu-configmap
externalCustomDatabase:
  datasourceRef: customdatasource-secret
  driverPvc: null
externalDatabase:
  databaseName: 'postgres'
  decisionCenter:
    databaseName: 'postgres'
    driversUrl: []
    password: 'postgres'
    port: '5432'
    secretCredentials: ''
    serverName: 'IBM-J8WGDY3'
    sslSecretRef: null
    type: 'postgres'
    url: ''
    user: 'postgres'
  decisionServer:
    databaseName: 'postgres'
    driversUrl: []
    password: 'postgres'
    port: '5432'
    secretCredentials: ''
    serverName: 'IBM-J8WGDY3'
    sslSecretRef: null
    type: 'postgres'
    url: ''
    user: 'postgres'
  driversUrl: []
  password: 'postgres'
  port: '5432'
  secretCredentials: ''
  serverName: 'IBM-J8WGDY3'
  sslSecretRef: null
  type: 'postgres'
  url: ''
  user: 'postgres'
image:
  arch: ''
  pullPolicy: IfNotPresent
  pullSecrets: null
  repository: 'cp.icr.io/cp/cp4a/odm'
  tag: 9.0.0.1-IF020
  useArch: false
internalDatabase:
  annotations: {}
  databaseName: null
  labels: {}
  password: null
  persistence:
    enabled: true
    resources:
      requests:
        storage: 5Gi
    storageClassName: ''
    useDynamicProvisioning: false
  populateSampleData: false
  resources:
    limits:
      cpu: 2
      ephemeral-storage: 1G
      memory: 4096Mi
    requests:
      cpu: 500m
      ephemeral-storage: 500Mi
      memory: 512Mi
  runAsUser: ''
  secretCredentials: ''
  tagOrDigest: null
  user: odmusr
license: true
livenessProbe:
  failureThreshold: 4
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 5
networkPolicy:
  egress: null
  enabled: true
  ingress: null
oidc:
  adminRef: null
  allowedDomains: null
  applyToComponents: []
  clientRef: null
  disableLoginPanel: null
  enabled: true
  initContainer:
    command: null
    configRef: null
    env: null
    existingClaimName: null
    image: null
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 100Mi
  keyAliasName: null
  mode: null
  provider: null
  redirectUrisRef: null
  registrationUrl: null
  serverUrl: null
readinessProbe:
  failureThreshold: 45
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
service:
  enableRoute: true
  enableTLS: true
  hostname: ''
  ingress:
    annotations: null
    class: null
    enabled: false
    host: null
    tlsHosts: []
    tlsSecretRef: null
  ipFamilies: null
  ipFamilyPolicy: null
  type: NodePort
serviceAccountName: ''
startupProbe:
  failureThreshold: 30
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
usersPassword: odmAdmin
vault:
  enabled: false
  type: ''
