pipeline {
    agent any
    stages {
        stage('Initialization') {
            steps {
                echo 'Initialization'

                // switch project namespace for ODM installation
                sh 'oc project odm-sandbox'

                // add helm repository for IBM Helm
                sh 'helm repo add ibm-helm https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm'
                sh 'helm repo update'
                
                // create secret for Entra ID TLS certificates
                sh 'oc delete secret ms-secret --ignore-not-found'
                sh 'oc create secret generic ms-secret \
                 --from-file=tls.crt=certificates/microsoft.crt'               
                sh 'oc delete secret digicert-secret --ignore-not-found'
                sh 'oc create secret generic digicert-secret \
                 --from-file=tls.crt=certificates/DigiCertGlobalRootG2.crt.pem'
                
                // replace AZUREAD_CLIENT_SECRET with credentials
                withCredentials([string(
                    credentialsId: 'AZUREAD_CLIENT_SECRET',
                    variable: 'AZUREAD_CLIENT_SECRET'
                )]) {
				    sh 'sed -i.bak "s|AZUREAD_CLIENT_SECRET|${AZUREAD_CLIENT_SECRET}|g" security/openIdParameters.properties'
				    sh 'sed -i.bak "s|AZUREAD_CLIENT_SECRET|${AZUREAD_CLIENT_SECRET}|g" security/openIdWebSecurity.xml'
				    sh 'sed -i.bak "s|AZUREAD_CLIENT_SECRET|${AZUREAD_CLIENT_SECRET}|g" security/OdmOidcProviders.json'
                }

                // create secret for Entra ID Web Security
                sh 'oc delete secret web-auth-secret --ignore-not-found'
                sh 'oc create secret generic web-auth-secret \
                 --from-file=openIdParameters.properties=security/openIdParameters.properties \
                 --from-file=openIdWebSecurity.xml=security/openIdWebSecurity.xml \
                 --from-file=webSecurity.xml=security/webSecurity.xml \
                 --from-file=OdmOidcProviders.json=security/OdmOidcProviders.json'

                // replace DC_DB_PASSWORD_SECRET with credentials
                withCredentials([string(
                    credentialsId: 'DC_DB_PASSWORD_SECRET',
                    variable: 'DC_DB_PASSWORD_SECRET'
                )]) {
				    sh 'sed -i.bak "s|DC_DB_PASSWORD_SECRET|${DC_DB_PASSWORD_SECRET}|g" datasource/datasource-dc.xml'
                }

                // create secret for datasources
                sh 'oc delete secret dcdv-datasource-secret --ignore-not-found'
                sh 'oc create secret generic dcdv-datasource-secret --from-file datasource/datasource-dc.xml --from-file datasource/datasource-ds.xml'

                // create configmap for jvm options
                sh 'oc delete configmap dc-jvm-options-configmap --ignore-not-found'
                sh 'oc create configmap dc-jvm-options-configmap --from-file jvm_options/dc-jvm-options'
                sh 'oc delete configmap dr-jvm-options-configmap --ignore-not-found'
                sh 'oc create configmap dr-jvm-options-configmap --from-file jvm_options/dr-jvm-options'
            }
        }

        stage('Deploy ODM Decision Center & Decision Runner to OCP') {
            steps {
                echo 'Deploy ODM DC & DV to OCP'
                script {
                    // read the Chart.yaml file from the workspace into a variable
                    def chart = readYaml file: 'charts/ibm-odm-prod/dcdv/Chart.yaml'

                    print "Helm chart name: ${chart.name}"
                    print "Helm chart version: ${chart.version}"
                    print "Helm chart app version: ${chart.appVersion}"

                    env.HELM_CHART_VERSION = "${chart.version}"
                    env.ODM_IMAGE_TAG = "${chart.appVersion}"
                }
                
                // replace ODM image tag with the appVersion from the chart
                sh 'sed -i.bak "s|ODM_IMAGE_TAG|${ODM_IMAGE_TAG}|g" charts/ibm-odm-prod/dcdv/values.yaml'

                // install ODM DC & DV using helm chart
                sh 'helm uninstall ibm-odm-dcdv-prod --ignore-not-found'
                sh 'helm install ibm-odm-dcdv-prod ibm-helm/ibm-odm-prod \
                 --version "${HELM_CHART_VERSION}" \
                 -f charts/ibm-odm-prod/dcdv/values.yaml \
                 --wait \
                 --timeout 30m'
            }
        }

        stage('Finalization') {
            steps {
                echo 'Finalization'
            }
        }
    }
}
