pipeline {
    agent any

    stages {
        stage('Initialization') {
            steps {
                echo 'Initialization'

                // switch project namespace for ODM installation
                sh 'oc project odm-sandbox'

                // add helm repository for IBM Helm
                sh 'helm repo add ibm-helm https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm'
                sh 'helm repo update'
                
                // create secret for Entra ID TLS certificates
                sh 'oc delete secret ms-secret --ignore-not-found'
                sh 'oc create secret generic ms-secret \
                 --from-file=tls.crt=certificates/microsoft.crt'               
                sh 'oc delete secret digicert-secret --ignore-not-found'
                sh 'oc create secret generic digicert-secret \
                 --from-file=tls.crt=certificates/DigiCertGlobalRootG2.crt.pem'
                
                // create secret for Entra ID Web Security
                sh 'oc delete secret web-auth-secret --ignore-not-found'
                sh 'oc create secret generic web-auth-secret \
                 --from-file=openIdParameters.properties=security/openIdParameters.properties \
                 --from-file=openIdWebSecurity.xml=security/openIdWebSecurity.xml \
                 --from-file=webSecurity.xml=security/webSecurity.xml'

                // create secret for datasources
                sh 'oc delete secret ds-datasource-secret --ignore-not-found'
                sh 'oc create secret generic ds-datasource-secret --from-file datasource/datasource-ds.xml'

                // create configmap for jvm options
                sh 'oc delete configmap dsc-jvm-options-configmap --ignore-not-found'
                sh 'oc create configmap dsc-jvm-options-configmap --from-file jvm_options/dsc-jvm-options'
                sh 'oc delete configmap dsr-jvm-options-configmap --ignore-not-found'
                sh 'oc create configmap dsr-jvm-options-configmap --from-file jvm_options/dsr-jvm-options'

                // create xu config for Decision Server Runtime
                sh 'oc delete configmap ds-runtime-xu-configmap --ignore-not-found'
                sh 'oc create configmap ds-runtime-xu-configmap --from-file xu_config/ds-runtime-xu'
                
                // create custom config app for mounting the custom config pvc
                sh 'oc delete deployment custom-config-app'
                sh 'oc apply -f deployment/custom-config-app.yaml'
                sh 'oc wait --for=condition=Ready=false \
                 pod/$(oc get pod -l run=custom-config-app -o jsonpath="{.items[0].metadata.name}") --timeout=300s'
 
                // copy custom configuration files for Decision Server Console to custom_config folder
                sh 'oc cp ./custom_config/application_dsc_custom.xml \
                 $(oc get pods -o jsonpath="{.items[0].metadata.name}" --selector=run=custom-config-app):/custom_config'
                sh 'oc cp ./custom_config/web_dsc_custom.xml \
                 $(oc get pods -o jsonpath="{.items[0].metadata.name}" --selector=run=custom-config-app):/custom_config'
                
                // copy custom configuration files for Decision Server Runtime to custom_config folder
                sh 'oc cp ./custom_config/application_dsr_custom.xml \
                 $(oc get pods -o jsonpath="{.items[0].metadata.name}" --selector=run=custom-config-app):/custom_config'
                sh 'oc cp ./custom_config/web_dsr_custom.xml \
                 $(oc get pods -o jsonpath="{.items[0].metadata.name}" --selector=run=custom-config-app):/custom_config'
            }
        }

        stage('Deploy ODM Decision Server Console and Decision Server Runtime to OCP') {
            steps {
                echo 'Deploy ODM DSC & DSR to OCP'
                // install ODM using helm chart
                sh 'helm uninstall ibm-odm-ds-prod --ignore-not-found'
                sh 'helm install ibm-odm-ds-prod ibm-helm/ibm-odm-prod \
                 --version 24.1.20 \
                 -f charts/ibm-odm-prod/ds/values.yaml \
                 --wait \
                 --timeout 30m'
            }
        }

        stage('Finalization') {
            steps {
                echo 'Finalization'
                // update decision server console deployment to add custom config mount
                sh 'oc patch deployment/ibm-odm-ds-prod-odm-decisionserverconsole \
                 --patch-file=patches/deployment/ibm-odm-ds-prod-odm-decisionserverconsole.yaml \
                 --type=strategic'

                // restart after changing the decision server console deployment
                sh 'oc scale deployment/ibm-odm-ds-prod-odm-decisionserverconsole --replicas=0'
                sh 'oc scale deployment/ibm-odm-ds-prod-odm-decisionserverconsole --replicas=1'

                // update decision server runtime deployment to add custom config mount
                sh 'oc patch deployment/ibm-odm-ds-prod-odm-decisionserverruntime \
                 --patch-file=patches/deployment/ibm-odm-ds-prod-odm-decisionserverruntime.yaml \
                 --type=strategic'

                // restart after changing the decision server runtime deployment
                sh 'oc scale deployment/ibm-odm-ds-prod-odm-decisionserverruntime --replicas=0'
                sh 'oc scale deployment/ibm-odm-ds-prod-odm-decisionserverruntime --replicas=1'
            }
        }
    }
}
